import type { Metadata } from "next";
import { Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { AppContextProvider } from "@/ui/context/AppContextProvider";
import { ContextMenu } from "@/ui/components/ContextMenu";

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const montserrat = Montserrat({
	variable: "--font-montserrat",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${montserrat.variable} ${geistMono.variable} antialiased`}>
				<AppContextProvider>
					<>
						<ContextMenu />
						<ToastContainer />
						{children}
					</>
				</AppContextProvider>
			</body>
		</html>
	);
}
